Memory Game
Project-Juniors-Club/jc-app pull request #140
Opened 2022-12-22 12:05 UTC by sltsheryl

Test on http://localhost:3000/test/memory

2022-12-23 08:11 UTC, kevinchua6 requested changes
Really great job Sheryl! Thanks for the very quick PR. 

Small nit: also run `yarn` instead of `npm install`, ditch npm for this project as we should stick to one (I see that your package-lock.json is updated)

2022-12-23 08:11 UTC, kevinchua6 commented on components/games/memory/CardFlipped.tsx
> +import React from 'react';
Good usage of separation of concerns

2022-12-23 08:11 UTC, kevinchua6 commented on components/games/memory/MemoryGame.tsx
> +  const randomiseCards = () => {
To make it more functional, probably can make `cards` a parameter for clarity

2022-12-23 08:11 UTC, kevinchua6 commented on components/games/memory/Cards.tsx
> +    flipped: false,
A small thing to take note during integration with BE (don't need to change now) - BE shouldn't need to pass `flipped` and `found` properties as they will always be false, can add it using the FE.

2022-12-23 08:11 UTC, kevinchua6 commented on components/games/memory/Cards.tsx
> +const Cards: Card[] = [
Cards should be small case as its not a jsx component - `cards`

2022-12-23 08:11 UTC, kevinchua6 commented on components/games/memory/Score.tsx
> +        {`Turns: `} {`${turns}`}
Can combine the two -        {\`Turns: ${turns}\`}

2022-12-23 08:11 UTC, kevinchua6 commented on package.json
> +    "styled-components": "^5.3.6",
use tailwind and css!!!!! :(

2022-12-29 04:57 UTC, sltsheryl commented
I have made changes based on feedback already

2022-12-31 10:40 UTC, kevinchua6 approved these changes
LGTM, good job!

2022-12-31 10:40 UTC, merged