feat(view-cart): access/modify localstorage, design for empty cart
Project-Juniors-Club/jc-app pull request #143
Opened 2022-12-24 16:51 UTC by kxrt

- cart populates from local storage
- cart saves to local storage on cancelling/proceeding
- removal should update cart
- add design for viewing empty carts

Additionally, standardised Open Sans font across the website.

Related to #102

2022-12-27 10:27 UTC, kevinchua6 requested changes

2022-12-27 10:27 UTC, kevinchua6 commented on pages/view-cart/index.tsx
> +    localStorage.setItem('Cart', JSON.stringify(cartCourses.filter((course, index: number) => checkedItems[index])));
If you cancel shouldn't you keep everything, even those that are not selected?

2022-12-27 10:27 UTC, kevinchua6 commented on pages/view-cart/index.tsx
> +    localStorage.setItem('Cart', JSON.stringify(cartCourses.filter((course, index: number) => checkedItems[index])));
I think we should store an array of courses together with whether they are selected or not instead. Feels strange if I go to the next page and quit the browser and only the selected courses remain.

2022-12-27 10:27 UTC, kevinchua6 commented on pages/view-cart/index.tsx
> +    localStorage.setItem('Cart', JSON.stringify(cartCourses.filter((course, index: number) => checkedItems[index])));
Also, store the course id instead of the entire course info and fetch the courseinfo via id using a useeffect. If we store all the properties of a course in localstorage, people can just change the values in localstorage and make the course free.

2023-01-10 06:13 UTC, kxrt commented on pages/view-cart/index.tsx
> +    localStorage.setItem('Cart', JSON.stringify(cartCourses.filter((course, index: number) => checkedItems[index])));
That's fair, had the wrong assumption. Corrected in the latest commit.

2023-01-10 07:17 UTC, kxrt commented on pages/view-cart/index.tsx
> +    localStorage.setItem('Cart', JSON.stringify(cartCourses.filter((course, index: number) => checkedItems[index])));
That makes sense - it's done!

2023-01-23 01:36 UTC, kevinchua6 approved these changes
LGTM

2023-01-23 01:36 UTC, merged