Add username from nextauth
Project-Juniors-Club/jc-app pull request #159
Opened 2023-01-09 17:50 UTC by sltsheryl

2023-01-11 05:29 UTC, MorningLit requested changes
For the component Dropdown can you change the ones highlighted?
![image](https://user-images.githubusercontent.com/57279935/211724797-8520f444-40ea-4f23-bf1a-bb7099705e05.png)
-For key, it should always be a unique key, in this case u can pass in item.clickOption
![image](https://user-images.githubusercontent.com/57279935/211724919-60c9c181-37c1-47f6-81b7-b930d464e5d8.png)
i think just having the bg be that color and not when it is hovered, is better

2023-01-11 05:36 UTC, MorningLit reviewed
![20230111133506_rec_](https://user-images.githubusercontent.com/57279935/211725796-c2e6ca44-f31b-45c6-b70b-f12e93678a96.gif)
Also can you remove the w-[775px] from all 3 navbars?

![20230111133403_rec_](https://user-images.githubusercontent.com/57279935/211725664-b6f3fbbc-aa07-4cfb-b222-ea0c82b9800b.gif)
So that we can achieve this (Up to you whether you wan to fix the first navbar, i can close an eye on it)

2023-01-11 18:25 UTC, sltsheryl commented
> So that we can achieve this (Up to you whether you wan to fix the first navbar, i can close an eye on it)

Should we collapse the nav bar like this? Or leaving it as the next row is better?
![Screenshot 2023-01-12 at 2 22 58 AM](https://user-images.githubusercontent.com/96589109/211887188-d2e21655-25a6-43fd-99db-e710fba5897f.png)

Currently, the new one is like this
![Screenshot 2023-01-12 at 2 23 59 AM](https://user-images.githubusercontent.com/96589109/211887448-1690fefa-c046-4583-9f48-43e9728950f6.png)

2023-01-13 06:55 UTC, MorningLit commented
@sltsheryl if you want you can go ahead, but I don't think there is figma design for it right(i think, if not I can't seem to find it).
And also I believe we aren't supporting mobile so we should only concern ourselves with 1024px (laptop min display resolution)
![image](https://user-images.githubusercontent.com/57279935/212256605-0c3a509d-1bf1-42bb-bc78-acc2e02595f8.png)

2023-01-13 07:00 UTC, MorningLit requested changes

2023-01-13 07:00 UTC, MorningLit commented on components/navbar/DropDown.tsx
> +            <Menu.Item as='div' key='item.clickOption' className={`block py-2 px-4`}>
Not the string 'item.clickOption' but {item.clickOption} instead

2023-01-13 07:05 UTC, MorningLit commented on components/navbar/DropDown.tsx
> +            <Menu.Item as='div' key='item.clickOption' className={`block py-2 px-4`}>
and i said remove the hover part only, not the entire bg-gray-100 😭

2023-01-13 08:00 UTC, sltsheryl commented on components/navbar/DropDown.tsx
> +            <Menu.Item as='div' key='item.clickOption' className={`block py-2 px-4`}>
> Not the string 'item.clickOption' but {item.clickOption} instead

Oh yea sry

2023-01-13 08:05 UTC, sltsheryl commented on components/navbar/DropDown.tsx
> +            <Menu.Item as='div' key='item.clickOption' className={`block py-2 px-4`}>
> and i said remove the hover part only, not the entire bg-gray-100 😭

Okay for easy reference, this is what's given in Figma ⬇️  I went to follow this
![Screenshot 2023-01-13 at 4 01 56 PM](https://user-images.githubusercontent.com/96589109/212268941-86d53a93-2df3-4d4a-9f90-a1a71dad0ff7.png)

2023-01-17 04:05 UTC, MorningLit approved these changes

2023-01-17 04:06 UTC, merged