Add Create account page
Project-Juniors-Club/jc-app pull request #16
Opened 2022-08-31 15:17 UTC by yunpeng1234

Address #9 

![image](https://user-images.githubusercontent.com/58326594/187714485-fd358aa8-cdde-43a6-885d-da2fe8c72664.png)

Basic validation and UI components are done. 

1. Alert box will pop when submitting different passwords
2. Successful validation resets form

Would suggest form validation libraries like Formik in the future

2022-09-01 00:31 UTC, kevinchua6 commented
1. Please help to create an issue to add form validation libraries such as Formik
2. Also need to set a minimum length for the password, possibly using Formik (create an issue)
3. The alert when passwords are different is also inconsistent: is there a way to make the behavior like email (with a dropdown message)?
![image](https://user-images.githubusercontent.com/45702380/187807598-93ff46d2-fefe-41ce-aa0e-f61d12234010.png)


Other than that, LGTM!

2022-09-02 03:52 UTC, yunpeng1234 commented
Issue #18 is added
Now the behaviour is defaulted to chakra UI form behaviour. After adding Formik it should be ok

2022-09-04 13:10 UTC, MorningLit commented
Can you try incorporating React Hook Forms, removing usestate from forms and also remove the window alert message?https://chakra-ui.com/getting-started/with-hook-form  Other than that it should be lgtm 😃

2022-09-05 07:58 UTC, yunpeng1234 commented
#18 
Incorporated React hook form and changed behavior of form to just indicate if field is valid. CI/CD fail due to Post.id

2022-09-06 09:18 UTC, MorningLit approved these changes

2022-09-08 06:20 UTC, MorningLit requested changes

2022-09-08 06:20 UTC, MorningLit commented on pages/users/create.tsx
> +                <FormLabel>Email</FormLabel>
remember to add htmlFor="email" here

2022-09-08 06:20 UTC, MorningLit commented on pages/users/create.tsx
> +              <FormControl isRequired isInvalid={Boolean(errors.email)}>
remove isRequired

2022-09-08 06:20 UTC, MorningLit commented on pages/users/create.tsx
> +              <FormControl isRequired isInvalid={Boolean(errors.email)}>
and also for other FormControls

2022-09-08 06:20 UTC, MorningLit commented on pages/users/create.tsx
> +                      required: 'Email is required',
Update required error message

2022-09-08 06:20 UTC, MorningLit commented on pages/users/create.tsx
> +                <FormLabel>Email</FormLabel>
and also for other labels

2022-09-08 06:20 UTC, MorningLit commented on pages/users/create.tsx
> +                      required: 'Email is required',
and also for ConfirmPassword

2022-09-08 07:32 UTC, MorningLit commented on pages/users/create.tsx
> +                <FormLabel>Email</FormLabel>
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label reason for the "for" attribute, i've also tried wrapping the label over the input but there was a small margin error

2022-09-08 10:09 UTC, yunpeng1234 commented
@MorningLit Fixed the changes requested 🙏 
@s7u4rt99 Create page as changed so don't override when merging recoil PR🙏

2022-09-09 04:36 UTC, kevinchua6 approved these changes
LGTM

2022-09-09 04:36 UTC, merged