Quiz Game
Project-Juniors-Club/jc-app pull request #163
Opened 2023-01-10 20:55 UTC by BryannYeap

* Have not run `db push` / `db migrate dev` yet in case it wiped the db, so could not test it

2023-01-11 03:20 UTC, weixin-tan requested changes
Thanks for helping. Some more important changes are:
1. Option type should be able to support both Image and Text together.
2. Questions need numbering.

Otherwise LGTM!

2023-01-11 03:20 UTC, weixin-tan commented on prisma/schema.prisma
> +model QuizGameQuestion {
Need numbering/order for the questions as well.

2023-01-11 03:20 UTC, weixin-tan commented on pages/api/quiz-game/[id].ts
> +              },
If `question.imageId` is undefined, this might throw an error. https://github.com/prisma/prisma/discussions/16976

Might be better to do conditional on the `image` level, aka
```
image: questions.imageId && { connect: ... }
```

2023-01-11 03:20 UTC, weixin-tan commented on pages/api/quiz-game/quizGameValidator.ts
> +import { SerializedQuizQuestion } from '../../../lib/server/quiz';
This file probably shouldn't be in the api page/folder? Good to have for frontend folder as well.

2023-01-11 03:20 UTC, weixin-tan commented on lib/server/quiz.ts
> +    quizGameOptionType: QuizGameOptionType;
Quiz Game Option can support both Text and Image simultaneously
<img width="565" alt="image" src="https://user-images.githubusercontent.com/58685069/211709287-e9fb03e4-872a-4748-91a0-7f875f2a66b8.png">

2023-01-12 08:31 UTC, BryannYeap commented on prisma/schema.prisma
> +  image
Done!

2023-01-12 08:31 UTC, BryannYeap commented on prisma/schema.prisma
> +model QuizGameQuestion {
Done!

2023-01-12 08:31 UTC, BryannYeap commented on pages/api/quiz-game/[id].ts
> +              },
Done!

2023-01-12 08:32 UTC, BryannYeap commented on pages/api/quiz-game/quizGameValidator.ts
> +import { SerializedQuizQuestion } from '../../../lib/server/quiz';
Shifted to `utils`!

2023-01-12 08:32 UTC, BryannYeap commented on lib/server/quiz.ts
> +    quizGameOptionType: QuizGameOptionType;
Done!

2023-01-13 08:53 UTC, closed without merging