Reset password logic + reset modal
Project-Juniors-Club/jc-app pull request #23
Opened 2022-09-04 10:41 UTC by remuskwan

**Note**: have yet to test update of user using prisma, as CRUD of user has yet to be completed
- Created a temporary forgot password page to demo forgot password link + forgot password modal at {domain}/forgot-password (actual link will be in login page)
![forgot-password-page](https://user-images.githubusercontent.com/36059985/188308854-bf6afc29-f697-455c-963e-abc6041e05c0.png)
- A password reset link will be sent to email address entered if it exists in the db.
- Public reset token is generated and a hashed version is stored as `passwordResetToken` in the `User` (updated `schema.prisma` for my use case)
![udpate-schema](https://user-images.githubusercontent.com/36059985/188309050-c3b3d1fb-66ad-4829-b673-a65fb963f8a2.png)
- Reset token appended to URL of reset link (open to suggestions for improvements on this design)
![ethereal-email](https://user-images.githubusercontent.com/36059985/188309152-0b01a75b-6b4a-4f2f-ad37-dcafedc17fbd.png)
- Used fake SMTP service for dev purposes. Add the following to your `.env`
![dotenv](https://user-images.githubusercontent.com/36059985/188309308-3a3cb4b4-5b69-4302-8d7e-f0d5fcfcf541.png)
- Reset link redirects user to reset password page at {domain}/reset-password/{reset-token}, where they can enter and update their new password
- Added basic input validation, awaiting Formik integration.
![reset-password](https://user-images.githubusercontent.com/36059985/188309366-99260e39-e152-4199-aa9f-9f40f3d0617e.png)

2022-09-06 08:53 UTC, MorningLit approved these changes
lgtm for frontend part, but currently facing the prisma db error so didn't had time to test out that part, i just assume it works
just need some small email validation for forget-password and nice modal component too 😍

2022-09-06 08:55 UTC, MorningLit commented on pages/reset-password/[token].tsx
> +      {/* TODO: replace with Formik */}
replace with react-hook-form

2022-09-06 09:11 UTC, weixin-tan commented
Brain fart + sausage finger on the PR closing. Please ignore. Thanks!

2022-09-10 03:41 UTC, kevinchua6 requested changes
Good job on this PR! :) Just a few lines to change

2022-09-10 03:41 UTC, kevinchua6 commented on lib/server/user.ts
> +export const findUser = async (where: Partial<Prisma.UserWhereInput>, select?: Prisma.UserSelect) => {
Nice use of types! :)

2022-09-10 03:41 UTC, kevinchua6 commented on pages/api/auth/forgotpassword/index.ts
> +        passwordResetAt: new Date(Date.now() + 10 * 60 * 1000),
If it's not too much trouble can you convert this to dayjs? Thanks!

2022-09-10 03:41 UTC, kevinchua6 commented on pages/api/auth/forgotpassword/index.ts
> +        passwordResetAt: new Date(Date.now() + 10 * 60 * 1000),
And maybe change the name to `passwordResetExpiryDate` or something, I was a bit confused when you checked `gt` later down in your code

2022-09-10 03:41 UTC, kevinchua6 commented on pages/forgot-password/index.tsx
> +    setIsLoading(true);
We have to remember to change the loading state here when react-query is added (in @kxrt's PR)

2022-09-10 03:41 UTC, kevinchua6 commented on pages/forgot-password/index.tsx
> +      const response = await fetch('/api/auth/forgotpassword', {
And use axios here as well

2022-09-10 03:41 UTC, kevinchua6 commented on pages/forgot-password/index.tsx
> +    setIsLoading(true);
Can you help to create an issue for this? Just a note for us to change all loading states to the one given by react-query

2022-09-10 07:25 UTC, kevinchua6 approved these changes
LGTM

2022-09-10 07:25 UTC, merged