feat: upload and display youtube video
Project-Juniors-Club/jc-app pull request #24
Opened 2022-09-05 05:10 UTC by hopinxian

Addresses #12 

Demos how to display a Youtube video given the video Id and upload a private Youtube video to an account.

<img width="534" alt="Capture" src="https://user-images.githubusercontent.com/40953322/188364127-cfa53a5f-7d3b-45d5-b757-052835cedce7.PNG">

Created a test google account at ```dscjuniorclub@gmail.com``` for video uploads. Will upload the password into the telegram chat. Requires downloading a client_secret.json file for authentication. You can download at the Google developer console. [here](https://console.developers.google.com) or [here](https://console.cloud.google.com/apis/credentials?project=steel-acumen-361413). 

<img width="960" alt="Capture" src="https://user-images.githubusercontent.com/40953322/188362775-415ab60d-030a-42e7-8410-fced543235bf.PNG">

During deployment, we may want to set up this authentication using the Food Bank Singapore Youtube account. Instructions to do so are [here](https://developers.google.com/youtube/v3/quickstart/nodejs#step_1_turn_on_the).

To view the uploaded videos, go to [studio youtube](https://studio.youtube.com) and click on content.

<img width="960" alt="Capture" src="https://user-images.githubusercontent.com/40953322/188364274-15d61742-9c06-4a06-8f1d-79b94a681e88.PNG">

Youtube Data Api has a quota. This quota is quite restrictive for testing purposes. More info on the quotas [here](https://developers.google.com/youtube/v3/determine_quota_cost). In brief, we have a quota of 10k credits daily. Uploading a single video takes 1.6k credits, so we can upload at most 6 videos a day. Business team might want to review the quotas link and check with Food Bank if this is acceptable. Alternatively, we may request for more quota using [this form](https://support.google.com/youtube/contact/yt_api_form) but am currently unable to find if this needs payments.

2022-09-06 14:28 UTC, hopinxian commented
Caveats: 

- The server is uploading a video read directly from the code base rather than being passed from the client webpage. Not expecting this to be an issue. 

Will upload a demo video in this PR to show the seamless-ness of this.

2022-09-10 03:19 UTC, kevinchua6 requested changes

2022-09-10 03:19 UTC, kevinchua6 commented on pages/test/youtube/index.tsx
> +import React from 'react';
Do `import { useState } from 'react';` instead

2022-09-10 03:19 UTC, kevinchua6 commented on pages/api/youtube/index.ts
> +const YoutubeUpload = async (videoTitle: string) => {
For helper functions, lets use lower case for the first letter (like setCookie):
![image](https://user-images.githubusercontent.com/45702380/189466269-17ac7ce9-59d0-4599-a3a8-362017c6bc8c.png)

https://nextjs.org/docs/api-routes/request-helpers

2022-09-10 03:19 UTC, kevinchua6 commented on pages/api/youtube/index.ts
> +    const videoId = await YoutubeUpload(videoTitle);
Clean code! :)

2022-09-10 03:19 UTC, kevinchua6 commented on pages/test/youtube/index.tsx
> +          await fetch(appUrl + 'api/youtube', requestOptions)
Can use axios instead of fetch!

2022-09-10 03:19 UTC, kevinchua6 commented on pages/api/youtube/index.ts
> +      onUploadProgress: evt => {
This is interesting!

2022-09-10 03:19 UTC, kevinchua6 commented on README.md
> +3. Create `.env` file with `DATABASE_URL` and `SYSTEMROOT=C:\Windows`
Is this a windows specific setting?

2022-09-11 12:32 UTC, hopinxian commented on README.md
> +3. Create `.env` file with `DATABASE_URL` and `SYSTEMROOT=C:\Windows`
`error - uncaughtException: Error: spawn undefined\System32\WindowsPowerShell\v1.0\powershell ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)
    at onErrorNT (node:internal/child_process:477:16)
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn undefined\\System32\\WindowsPowerShell\\v1.0\\powershell',
  path: 'undefined\\System32\\WindowsPowerShell\\v1.0\\powershell',
  spawnargs: [
    '-NoProfile',
    '-NonInteractive',
    '–ExecutionPolicy',
    'Bypass',
    '-EncodedCommand',
    'UwB0AGEAcgB0ACAAIgBoAHQAdABwAHMAOgAvAC8AYQBjAGMAbwB1AG4AdABzAC4AZwBvAG8AZwBsAGUALgBjAG8AbQAvAG8ALwBvAGEAdQB0AGgAMgAvAHYAMgAvAGEAdQB0AGgAPwByAGUAZABpAHIAZQBjAHQAXwB1AHIAaQA9AGgAdAB0AHAAJQAzAEEAJQAyAEYAJQAyAEYAbABvAGMAYQBsAGgAbwBzAHQAJQAzAEEAOAAwADgAMAAlADIARgAmAGEAYwBjAGUAcwBzAF8AdAB5AHAAZQA9AG8AZgBmAGwAaQBuAGUAJgBzAGMAbwBwAGUAPQBoAHQAdABwAHMAJQAzAEEAJQAyAEYAJQAyAEYAdwB3AHcALgBnAG8AbwBnAGwAZQBhAHAAaQBzAC4AYwBvAG0AJQAyAEYAYQB1AHQAaAAlADIARgB5AG8AdQB0AHUAYgBlAC4AdQBwAGwAbwBhAGQAJQAyADAAaAB0AHQAcABzACUAMwBBACUAMgBGACUAMgBGAHcAdwB3AC4AZwBvAG8AZwBsAGUAYQBwAGkAcwAuAGMAbwBtACUAMgBGAGEAdQB0AGgAJQAyAEYAeQBvAHUAdAB1AGIAZQAmAHIAZQBzAHAAbwBuAHMAZQBfAHQAeQBwAGUAPQBjAG8AZABlACYAYwBsAGkAZQBuAHQAXwBpAGQAPQAxADAAMAA0ADkAMQA1ADgAOAAxADgAOQAtAHIAcwB2AGoAZgBqAHEAMwBsAGQAZABkAGoAdgBsADUAbQAwADAAYgBqAG4AMwB1AGMANQBzADkAcQBnAGwAZQAuAGEAcABwAHMALgBnAG8AbwBnAGwAZQB1AHMAZQByAGMAbwBuAHQAZQBuAHQALgBjAG8AbQAiAA=='
  ]
}`

Without that setting, I receive the above error which is caused when SYSTEM_ROOT is not defined. 

Are you using a windows or a mac? Could I ask you to help pull this branch and check if the API works without setting SYSTEMROOT?

2022-09-13 09:43 UTC, BryannYeap commented on README.md
> +4. Download client_secret.json from dscJuniorClub@gmail.com Google Developer Console into the root folder. Add the client_secret field into the json.
The `client_secret.json` file name is always the same, so it can be added to the `.gitignore` file.

2022-09-13 09:43 UTC, BryannYeap commented on pages/api/youtube/index.ts
> +    res.status(500).json({ statusCode: 500, videoId: 'O-yi0LBDi3s' });
Trying to access this API using a GET request leads to a 500 status code, which usually refers to an internal server error.  However, a GET request should not be allowed, so perhaps a 400 status code (bad request) or 405 status code (method not allowed) would be more appropriate for this case.

Here is a possible solution: https://stackoverflow.com/questions/66739797/how-to-handle-a-post-request-in-next-js

Another possible solution: 
![image](https://user-images.githubusercontent.com/77266823/189866919-9f8da155-a2cd-45b5-92fa-2f4fb60a6fd1.png)

2022-09-13 09:43 UTC, BryannYeap commented on pages/api/youtube/index.ts
> +  console.log(res.data);
Might be a bad idea to have console.log in production, same with line 16 above.

2022-09-13 12:02 UTC, hopinxian commented on pages/api/youtube/index.ts
> +    res.status(500).json({ statusCode: 500, videoId: 'O-yi0LBDi3s' });
Thank you! This is a really nice resource.

2022-09-21 10:49 UTC, hopinxian commented on README.md
> +3. Create `.env` file with `DATABASE_URL` and `SYSTEMROOT=C:\Windows`
Verified with Sheryl that this works on a Mac without the SYSTEM_ROOT definition

2022-09-21 13:44 UTC, hopinxian commented on pages/test/youtube/index.tsx
> +  const [videoTitle, setVideoTitle] = React.useState('');
Done

2022-09-21 13:44 UTC, hopinxian commented on pages/test/youtube/index.tsx
> +import React from 'react';
Done

2022-09-21 13:44 UTC, hopinxian commented on pages/api/youtube/index.ts
> +const YoutubeUpload = async (videoTitle: string) => {
Done

2022-09-21 13:45 UTC, hopinxian commented on pages/test/youtube/index.tsx
> +          await fetch(appUrl + 'api/youtube', requestOptions)
done

2022-09-21 13:46 UTC, hopinxian commented on pages/api/youtube/index.ts
> +  console.log(res.data);
done

2022-09-21 13:52 UTC, hopinxian commented
rebased and added the postman docs

2022-11-05 10:38 UTC, kevinchua6 commented
Can you help fix the merge conflicts so I can merge this in? thank you!

2022-12-22 02:33 UTC, kevinchua6 commented
Btw u can do an empty commit using `git commit --allow-empty`

2022-12-22 02:33 UTC, kevinchua6 approved these changes

2022-12-22 02:33 UTC, merged