Stuart/recoil setup
Project-Juniors-Club/jc-app pull request #31
Opened 2022-09-06 09:09 UTC by s7u4rt99

Resolves #3 
* Add redirect to log in page #16 
* Log in page no functionality yet, lets everyone in
* Home page will display name, email and role

2022-09-08 07:01 UTC, MorningLit requested changes

2022-09-08 07:01 UTC, MorningLit commented on components/RouteGuard.tsx
> +    const [authorized, setAuthorized] = useRecoilState(authorizedState);
we are using next-auth so this file is not needed 😭

2022-09-08 07:01 UTC, MorningLit commented on pages/users/create.tsx
> +import { useForm } from 'react-hook-form';
either remove this or wait for yunpeng's MR to be merged

2022-09-09 04:20 UTC, kevinchua6 requested changes

2022-09-09 04:20 UTC, kevinchua6 commented on atoms/atoms.ts
> +        const role = get(roleState);
Can you store everything in one single state?
like:
```userInfoState = atom({
key: 'userInfo',
default: {
email: "",
fullName: '',
etc...
}
})```

2022-09-09 04:20 UTC, kevinchua6 commented on atoms/atoms.ts
> +            set(nameState, value);
What does this mean? Why do you set all the values to the same value when it's a default value?

2022-09-09 04:20 UTC, kevinchua6 commented on atoms/atoms.ts
> +            set(nameState, value);
Can you also fix this error? Thank you!
<img width="1020" alt="image" src="https://user-images.githubusercontent.com/45702380/189271071-c379d943-7678-4244-9c55-c16eaba97f62.png">

2022-09-11 09:46 UTC, s7u4rt99 commented on components/RouteGuard.tsx
> +    const [authorized, setAuthorized] = useRecoilState(authorizedState);
Alright! Was just using it to test the recoil state, will delete this class later 😄  Thanks!

2022-09-11 09:46 UTC, s7u4rt99 commented on pages/users/create.tsx
> +import { useForm } from 'react-hook-form';
Ok

2022-09-11 09:49 UTC, s7u4rt99 commented on atoms/atoms.ts
> +        const role = get(roleState);
Yes can, but it comes with some limitation such as not being able to read/write each one of them individually (have to read/write all together) based on [this](https://stackoverflow.com/questions/69943153/multiple-form-values-in-one-react-recoil-atom-override-each-other). 

Do you think I should still combine them?

2022-09-11 09:50 UTC, s7u4rt99 commented on atoms/atoms.ts
> +            set(nameState, value);
Ok will fix these!

2022-09-11 10:01 UTC, s7u4rt99 commented on atoms/atoms.ts
> +            set(nameState, value);
Apparently this error does not have an official solution yet until now, and what people have done is just to mute it. Should I just mute the error? It seems to be a limitation of recoil with nextjs. [Link to issue](https://github.com/facebookexperimental/Recoil/issues/733)

2022-09-11 12:13 UTC, kevinchua6 commented on atoms/atoms.ts
> +            set(nameState, value);
I think we should just mute the error then, thanks!

2022-09-11 12:18 UTC, kevinchua6 commented on atoms/atoms.ts
> +        const role = get(roleState);
Alright, this seems ok then (although it feels a bit like overengineering to me), let's just leave it! 😄

2022-09-13 08:31 UTC, MorningLit commented on atoms/atoms.ts
> +            set(nameState, value);
What does this mean? Why do you set all the values to the same value when it's a default value?

2022-09-13 08:34 UTC, MorningLit requested changes

2022-09-13 08:34 UTC, MorningLit commented on pages/users/create.tsx
> +  const [authorized, setAuthorized] = useRecoilState(authorizedState);
We'll be using nextauth for authorization so we'll be using useSession().status to check our authorization. 😭

2022-09-13 08:34 UTC, MorningLit commented on atoms/atoms.ts
> +export const authorizedState = atom({
can remove 😢

2022-09-13 08:34 UTC, MorningLit commented on pages/users/create.tsx
> +  useEffect(() => {
remove useEffect

2022-09-13 09:49 UTC, kevinchua6 commented on pages/users/create.tsx
> +  const setName = useSetRecoilState(nameState);
Use your setter in userInfoState since you're setting everything together anyway

2022-09-13 17:10 UTC, s7u4rt99 commented on pages/users/create.tsx
> +  const [authorized, setAuthorized] = useRecoilState(authorizedState);
ok removed

2022-09-13 17:10 UTC, s7u4rt99 commented on atoms/atoms.ts
> +export const authorizedState = atom({
ok removed

2022-09-13 17:11 UTC, s7u4rt99 commented on pages/users/create.tsx
> +  useEffect(() => {
ok removed

2022-09-13 17:40 UTC, s7u4rt99 commented on atoms/atoms.ts
> +            set(nameState, value);
Sorry was boiler plate code, for setters of selectors, there is a chance that someone calls `useResetRecoilState()`, therefore we must handle that case as well.

2022-09-13 17:41 UTC, s7u4rt99 commented on pages/users/create.tsx
> +  const setName = useSetRecoilState(nameState);
ok done

2022-09-14 08:08 UTC, kevinchua6 approved these changes
LGTM

2022-09-27 12:41 UTC, MorningLit approved these changes
lgtm

2022-09-27 12:42 UTC, MorningLit commented
Help to resolve merge conflicts please😭 and it'll be merged

2022-10-17 07:01 UTC, s7u4rt99 commented
@MorningLit Done! Would u like to check it one last time?

2022-10-18 09:17 UTC, merged