Add login page
Project-Juniors-Club/jc-app pull request #33
Opened 2022-09-06 13:47 UTC by kxrt

- Create login page on route '/login'
- Implement regex check on email to validate inputs better
- Add 'Login' object to Layout bar
- Implement usage of snackbars on successful/unsuccesful login attempt
- Set up basic styling, using UI colors from Trello

<img width="1436" alt="Login Page" src="https://user-images.githubusercontent.com/73589885/188651576-0bcaef14-957f-4bb8-a5d3-5041a54daa45.png">

2022-09-08 07:16 UTC, MorningLit commented
Where did you get the design from?

2022-09-08 07:23 UTC, MorningLit commented on pages/login/index.tsx
> +            p={8}
height overflow because of this padding

2022-09-08 07:23 UTC, MorningLit commented on pages/login/index.tsx
> +  const [isValidEmail, setIsValidEmail] = useState(true); // So that error does not pop up on first visit
i'm sorry but please use react-hook-form 😭

2022-09-08 07:23 UTC, MorningLit commented on pages/login/index.tsx
> +            p={8}
either move this padding to the outerest most Box or remove it

2022-09-08 07:23 UTC, MorningLit commented on pages/login/index.tsx
> +              height='100vh'
height 100% can be used here

2022-09-08 07:23 UTC, MorningLit commented on pages/login/index.tsx
> +                  <FormLabel htmlFor='email'>Email</FormLabel>
![image](https://user-images.githubusercontent.com/57279935/189060348-9a172496-195b-42f0-8834-1a8ad333b851.png)
title and labels are white on dark theme

2022-09-09 04:32 UTC, kevinchua6 requested changes

2022-09-09 04:32 UTC, kevinchua6 commented on pages/login/index.tsx
> +      const res = await fetch('/api/auth/login', {
Can you help me to change this to react query? Thanks!

2022-09-09 04:32 UTC, kevinchua6 commented on pages/login/index.tsx
> +    setIsLoading(true);
loading also can be replaced by react query!

2022-09-09 04:32 UTC, kevinchua6 commented on pages/login/index.tsx
> +                <FormControl isRequired isInvalid={!isValidEmail} mt={4} width={{ sm: '80vw', md: '80vw', lg: '500px' }}>
Good job making this responsive!!

2022-09-09 08:14 UTC, kxrt commented on pages/login/index.tsx
> +            p={8}
Done!

2022-09-09 08:14 UTC, kxrt commented on pages/login/index.tsx
> +  const [isValidEmail, setIsValidEmail] = useState(true); // So that error does not pop up on first visit
Done!

2022-09-09 08:16 UTC, kxrt commented on pages/login/index.tsx
> +                  <FormLabel htmlFor='email'>Email</FormLabel>
Should be fixed now!

2022-09-09 08:18 UTC, kxrt commented on pages/login/index.tsx
> +                <FormControl isRequired isInvalid={!isValidEmail} mt={4} width={{ sm: '80vw', md: '80vw', lg: '500px' }}>
Thanks!

2022-09-09 08:20 UTC, kxrt commented on pages/login/index.tsx
> +      const res = await fetch('/api/auth/login', {
Should I be using Axios here too? I'm not sure of the API's url.

2022-09-09 08:22 UTC, kxrt commented
> Where did you get the design from?

@MorningLit I searched up "split login page" for inspiration and free-hand edited from there.

2022-09-09 08:23 UTC, kxrt commented on pages/login/index.tsx
> +              height='100vh'
Done!

2022-09-10 02:30 UTC, kevinchua6 commented on pages/login/index.tsx
> +      const res = await fetch('/api/auth/login', {
yes please! yeah the api isn't done yet so just put a placeholder url in the meantime

2022-09-10 16:01 UTC, kxrt commented on pages/login/index.tsx
> +      const res = await fetch('/api/auth/login', {
Done!

2022-09-10 16:01 UTC, kxrt commented on pages/login/index.tsx
> +    setIsLoading(true);
Done!

2022-09-11 11:59 UTC, kevinchua6 requested changes
Looks good, just some small nits!

2022-09-11 11:59 UTC, kevinchua6 commented on pages/login/index.tsx
> +  const mutation = useMutation(login, {
Good job :)

2022-09-11 11:59 UTC, kevinchua6 commented on pages/login/index.tsx
> +                    {(errors.email || mutation.isError) && <FormErrorMessage>Please enter a valid email address.</FormErrorMessage>}
This is when the user enters a wrong username and password combination right? I feel that this error message is incorrect (an email is valid, just that it doesn't match the password). Maybe just remove this and put `Incorrect username or password. ` under the password field when the user fails to log in?

2022-09-11 11:59 UTC, kevinchua6 commented on pages/login/index.tsx
> +      window.location.href = '/';
Use router.push instead, I think a native nextjs solution is better

2022-09-11 11:59 UTC, kevinchua6 commented on pages/login/index.tsx
> +const url = '/api/auth/login';
I think we should capitalise the variable name for this

2022-09-11 11:59 UTC, kevinchua6 commented on pages/login/index.tsx
> +    console.log(data);
Please remove this, thanks

2022-09-11 17:26 UTC, kxrt commented on pages/login/index.tsx
> +    console.log(data);
Done!

2022-09-11 17:26 UTC, kxrt commented on pages/login/index.tsx
> +const url = '/api/auth/login';
Makes sense, missed this out. Done!

2022-09-11 17:26 UTC, kxrt commented on pages/login/index.tsx
> +      window.location.href = '/';
Edited!

2022-09-11 17:26 UTC, kxrt commented on pages/login/index.tsx
> +  const mutation = useMutation(login, {
Thanks :)

2022-09-11 17:28 UTC, kxrt commented on pages/login/index.tsx
> +                    {(errors.email || mutation.isError) && <FormErrorMessage>Please enter a valid email address.</FormErrorMessage>}
Done with a slight modification - there's still an invalid email address error when it fails regex (through `errors.email`).

2022-09-13 08:44 UTC, MorningLit approved these changes
![image](https://user-images.githubusercontent.com/57279935/189855125-8062f636-eddb-4fa2-9d19-030d18cbcef9.png)
there's still some issue with the design 🙈 , but since this isn't the finalised UED design, lgtm!

2022-09-13 08:44 UTC, MorningLit commented on pages/login/index.tsx
> +const URL = '/api/auth/login';
move this to utils/ folder and create a link file to store all the URL links in one place

2022-09-13 08:59 UTC, kxrt commented on pages/login/index.tsx
> +const URL = '/api/auth/login';
Done!

2022-09-14 14:57 UTC, kevinchua6 approved these changes
LGTM, just merge master into it and it's fine

2022-09-14 15:18 UTC, merged