CRUD endpoints for Courses
Project-Juniors-Club/jc-app pull request #44
Opened 2022-09-12 17:53 UTC by s7u4rt99

Resolves #36

2022-09-13 11:04 UTC, BryannYeap reviewed
Almost LGTM! Just a few nits.

2022-09-13 11:04 UTC, BryannYeap commented on pages/api/courses/index.ts
> +        res.status(400).json({ message: error })
I believe we should default to a status code of 500 here, as any unhandled errors here is the server's fault, since the client has already sent a valid request. If the client sends a request with an invalid JSON body, it already seems to automatically give a 400 status code.

2022-09-13 11:04 UTC, BryannYeap commented on pages/api/courses/[id].ts
> +        res.status(400).json({ message: error })
Same comment as in `index.ts`

2022-09-13 17:09 UTC, s7u4rt99 commented on pages/api/courses/[id].ts
> +            const courses = await prisma.course.findFirst({
done

2022-09-13 17:09 UTC, s7u4rt99 commented on pages/api/courses/index.ts
> +        res.status(400).json({ message: error })
done

2022-09-13 17:09 UTC, s7u4rt99 commented on pages/api/courses/[id].ts
> +        res.status(400).json({ message: error })
done

2022-09-16 16:33 UTC, BryannYeap approved these changes
LGTM!

2022-10-04 13:27 UTC, kevinchua6 requested changes
Looks good, just follow the message and data response conventions given in https://github.com/Project-Juniors-Club/jc-app/pull/53, and update postman also

2022-10-06 06:37 UTC, weixin-tan commented
Take note of #60, might be able to do within this PR. Or separate if the migration is not too tricky.

2022-10-21 18:45 UTC, s7u4rt99 commented
Added message and data responses, and incorporated with the extra fields added to courses on main. Not sure what is needed to add to postman @kevinchua6

2022-10-27 06:02 UTC, kevinchua6 commented
Looks good, can you update postman with a sample body with name, description etc so I can test it, thanks!
![image](https://user-images.githubusercontent.com/45702380/198203614-d1631d3c-9e96-4a1a-9e07-7260e0c3d9b5.png)

2022-10-30 17:17 UTC, s7u4rt99 commented
done @kevinchua6

2022-11-01 02:35 UTC, kevinchua6 approved these changes
LGTM

2022-11-01 02:35 UTC, merged