feat: add CRUD API for spot the difference game
Project-Juniors-Club/jc-app pull request #49
Opened 2022-09-13 13:20 UTC by hopinxian

Creating a draft pull request for status update. Yet to test the APIs.

Additional things to do: 
- Setting up sample data for the games
- Adding validators to ensure the data for differences are valid

2022-09-14 15:05 UTC, kevinchua6 commented
Also rmb to update Postman docs with your new endpoints as well (so it's easier for me to test also) https://github.com/Project-Juniors-Club/jc-app/tree/main/docs

2022-09-21 13:10 UTC, hopinxian commented
@kevinchua6  @BryannYeap to seek your opinions

I think there needs to be other issues that get resolved first before this PR and why I think so is below.

The way I imagine the app is that there is a page on the frontend, where the admin will be modifying the content of a specific course.
He wants to add to a specific page, a spot the difference game.
On this page, he uploads two images, clicks on the locations of the differences and presses upload.

There are two ways the frontend can interact with the backend.

### Method 1 
Frontend sends a **single** API request to create a spot the difference game with the following information
- course Id
- page number
- two image data (not url)
- location differences

Backend is then required to 
- create the course item in the database
- upload two images and get the image url
- create the image in the database
- create the game in the difference

### Method 2
Frontend makes multiple API requests to the backend. (e.g. first uploading the image, then creating the game).

I feel the first way is more ideal. But regardless, the backend is composed of many steps of which only the last is currently implemented in this PR. 

I propose to split the backend steps into multiple issues which we will handle in separate PRs first before handling this PR.
The main reason is that the first three functionality is likely shared with the other PRs on games. 

Another reason, is that it is going to be troublesome to test this PR when you do not have the image Id to send in the POST request.

2022-09-21 13:11 UTC, hopinxian commented
>

2022-09-22 08:22 UTC, kevinchua6 requested changes
Good job! A few small changes

2022-09-22 08:22 UTC, kevinchua6 commented on pages/api/spot-difference-game/[id].ts
> +            const game = await prisma.spotTheDifferenceGame.findFirst({
Why not [`findUnique`](https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#findunique)?

2022-09-22 08:22 UTC, kevinchua6 commented on pages/api/spot-difference-game/[id].ts
> +export default async function handler(req: NextApiRequest, res: NextApiResponse) {
Let's try to keep this consistent, and use arrow functions for all the functions (also applies to spotTheDifferenceValidator etc)

2022-09-22 08:22 UTC, kevinchua6 commented on pages/api/spot-difference-game/spotTheDifferenceValidator.ts
> +    for(const location of differences) {
Have you set up prettier? It should catch the spacing between `for(` for you. You can try to test if prettier fixes this for you

2022-09-22 08:22 UTC, kevinchua6 commented on pages/api/spot-difference-game/spotTheDifferenceValidator.ts
> +        return { valid: false, message: "The number of values should be a multiple of 4." };
Hmm, are they multiples of 4 because you're defining a rectangle?

2022-09-22 08:22 UTC, kevinchua6 commented on pages/api/spot-difference-game/spotTheDifferenceValidator.ts
> +    if (differences.length % 4 != 0) {
I think it should be `!==` instead of `!=`

2022-09-23 02:58 UTC, hopinxian commented on pages/api/spot-difference-game/spotTheDifferenceValidator.ts
> +        return { valid: false, message: "The number of values should be a multiple of 4." };
Yes, that is the case.

2022-09-28 05:19 UTC, kevinchua6 commented
Regarding method 1 vs method 2, I agree that method 1 is definitely better and we should do it. However we should also take note that the product side wants a shared asset pool (we specify the images we have from an image library and choose which images to add it to a course or a page) so ideally we should probably expose both endpoints. 

Either way, we need to wait for the image CRUD to be done before doing anything here

2022-10-01 10:31 UTC, hopinxian commented on pages/api/spot-difference-game/[id].ts
> +            const game = await prisma.spotTheDifferenceGame.findFirst({
I see. Shall use findUnique since it is not dependent on findMany

2022-10-01 10:31 UTC, hopinxian commented on pages/api/spot-difference-game/[id].ts
> +export default async function handler(req: NextApiRequest, res: NextApiResponse) {
Sure

2022-10-01 10:32 UTC, hopinxian commented
Thanks for the clarification. This helps me better understand how the API should be structured.

2022-10-04 08:28 UTC, hopinxian commented
An additional note however is that our current DB structure does not allow keeping a shared asset pool.

Each Image is a Course Item and each Course Item must belong to a Course.

2022-10-10 06:58 UTC, hopinxian commented on pages/api/spot-difference-game/spotTheDifferenceValidator.ts
> +    for(const location of differences) {
Sure

2022-10-20 01:49 UTC, weixin-tan commented
Please merge master into this branch to make sure that its working.

2022-10-25 12:45 UTC, hopinxian commented
This PR has a dependency on the course PR  #44

2022-11-01 03:26 UTC, kevinchua6 commented
Stuart's Course CRUD branch has been merged, can you resolve the conflicts (and also follow this https://github.com/Project-Juniors-Club/jc-app/pull/99 for API messages/errors)? thank you!

2022-11-01 14:55 UTC, hopinxian commented
I have fixed the merge conflicts and updated to use the API message/errors.

2022-11-05 10:59 UTC, kevinchua6 approved these changes

2022-11-05 11:01 UTC, merged