Simple frontend page and api to connect to s3 bucket
Project-Juniors-Club/jc-app pull request #80
Opened 2022-10-11 16:17 UTC by jengoc415

Still have problem with aws connection. Just submitting a intermediate pull request.

2022-10-12 06:13 UTC, kxrt reviewed
Just some style changes required to pass checks once the AWS bucket is accessible!

2022-11-01 03:35 UTC, kevinchua6 requested changes

2022-11-01 03:35 UTC, kevinchua6 commented on pages/api/media/index.ts
> +    region: "ap-southeast-1",
please use 2 spaces indent instead of 4

2022-11-01 03:35 UTC, kevinchua6 commented on pages/api/media/index.ts
> +        if (method == 'GET') {
Good job having accurate error messages! :)

2022-11-01 03:35 UTC, kevinchua6 commented on pages/api/media/index.ts
> +            res.status(200).json({message: messages.getFilesSuccess});
You don't return your result? I think it should be 
`res.status(200).json({message: messages.getFilesSuccess, data: result});`

2022-11-01 03:35 UTC, kevinchua6 commented on pages/api/media/index.ts
> +            res.status(200).json({message: messages.uploadFileSuccess});
Same for this, our convention is that we return the object that we modified

2022-11-01 03:35 UTC, kevinchua6 commented on pages/api/media/index.ts
> +            res.status(200).json({message: messages.deleteFileSuccess});
this also

2022-11-01 03:35 UTC, kevinchua6 commented on pages/uploads/index.tsx
> +// export async function getServerSideProps(context) {
remove

2022-11-01 03:35 UTC, kevinchua6 commented on pages/uploads/upload.tsx
> +        Here, you can upload media files to our very own AWS bucket. Free limit is 5GB pls do not test with huge files!!
hahaha

2022-11-04 04:00 UTC, kevinchua6 commented
just a note, rmb to follow commit conventions, thanks!

2022-11-04 04:02 UTC, kevinchua6 approved these changes

2022-11-04 04:03 UTC, merged