Add buttons
Project-Juniors-Club/jc-app pull request #98
Opened 2022-10-30 11:07 UTC by yunpeng1234

![image](https://user-images.githubusercontent.com/58326594/198875394-c49c2911-39f3-4d9d-a628-9923a50e8fc4.png)
This how the buttons looks like as of now

2022-11-01 07:09 UTC, yunpeng1234 commented
Changed to 1 component with variant fields.
`green-solid green-outline black-solid black-outline`

2022-11-01 10:14 UTC, kevinchua6 commented on components/Buttons.tsx
> +  variant: String;
btw this variant should be an enum right? and String should be small letter iirc

2022-11-01 10:15 UTC, kevinchua6 commented on components/Buttons.tsx
> +  variant: 'green-solid' | 'green-outline' | 'black-solid' | 'black-outline';
oh nvm u changed it alr

2022-11-01 11:09 UTC, MorningLit requested changes

2022-11-01 11:14 UTC, MorningLit commented on components/Buttons.tsx
> +  icon: ReactNode;
ignore my comment on the left and right side

2022-11-01 11:16 UTC, MorningLit commented
![image](https://user-images.githubusercontent.com/57279935/199221155-0e7ffac0-edae-4dec-9e0f-c4bbd4740716.png)
try and follow the ui format as shown, specifically the size part

2022-11-01 11:18 UTC, MorningLit commented on components/Buttons.tsx
> +  text?: String;
actually lets remove text as a prop, we will take in children props and place our children within the <button>tags
eg. <button>{children}</button>

2022-11-01 11:40 UTC, yunpeng1234 commented
> ![image](https://user-images.githubusercontent.com/57279935/199221155-0e7ffac0-edae-4dec-9e0f-c4bbd4740716.png) try and follow the ui format as shown, specifically the size part

Sorry but what is ghost button

2022-11-04 03:51 UTC, kevinchua6 requested changes
Good job on the PR, just some changes needed

2022-11-04 03:51 UTC, kevinchua6 commented on components/Buttons.tsx
> +import { JsxElement } from 'typescript';
Not used, remove this thanks!

2022-11-04 03:51 UTC, kevinchua6 commented on components/Buttons.tsx
> +import { Center, HStack, Spinner, Text } from '@chakra-ui/react';
Remove HStack, Text and Component imports as they are unused

2022-11-04 03:51 UTC, kevinchua6 commented on components/Buttons.tsx
> +  console.log(styling);
remove

2022-11-04 03:51 UTC, kevinchua6 commented on components/Buttons.tsx
> +const getConfig = (variant: string) => {
extract out type ('green-solid' | 'green-outline' | 'black-solid' | 'black-outline') on line 10 into a type Variants and use it as a type here

2022-11-04 03:51 UTC, kevinchua6 commented on components/Buttons.tsx
> +    if (variant == 'black-solid') {
3 equals

2022-11-04 03:51 UTC, kevinchua6 commented on components/Buttons.tsx
> +    <button className={styling} disabled={isDisabled} onClick={onClick}>
gj using tailwind

2022-11-04 03:51 UTC, kevinchua6 commented on components/Buttons.tsx
> +type Props = {
add a className prop as well, so we can inject height, width properties etc into the button

eg
![image](https://user-images.githubusercontent.com/45702380/199881440-5b5ad2a8-cada-455a-8f0d-86a8a51f0e40.png)

2022-12-02 01:46 UTC, kevinchua6 approved these changes

2022-12-02 01:51 UTC, merged